"""add_base_model

Revision ID: 2e163039cbde
Revises: 960729ac9cc1
Create Date: 2025-01-01 21:37:48.125324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e163039cbde'
down_revision: Union[str, None] = '960729ac9cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('customer', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'updated_at')
    op.drop_column('customer', 'created_at')
    # ### end Alembic commands ###
